trigger:
- none
stages:
- stage: Build
  jobs:
    - job: Build
      displayName: Building IWA Project
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
    - job: SAST
      displayName: Fortify SAST
      dependsOn:
       - Build
      pool:
       vmImage: 'ubuntu-latest'
      container:
        image: fortifydocker/fortify-ci-tools:latest-jdk-17
        env:
          FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN: $(FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN)
          FCLI_DEFAULT_SSC_USER: $(FCLI_DEFAULT_SSC_USER)
          FCLI_DEFAULT_SSC_PASSWORD: $(FCLI_DEFAULT_SSC_PASSWORD)
          FCLI_DEFAULT_SSC_CI_TOKEN: $(FCLI_DEFAULT_SSC_CI_TOKEN)
          FCLI_DEFAULT_SSC_URL: $(FCLI_DEFAULT_SSC_URL)
          SSC_APP: $(SSC_APP)
          SC_SAST_SENSOR_VERSION: 24.4
      steps:
      - script: |
          echo Setting connection with Fortify Platform
          fcli ssc session login
          fcli sc-sast session login

          fcli ssc appversion create $(SSC_APP) --auto-required-attrs --skip-if-exists --issue-template "Prioritized High Risk Issue Template" --add-users "jwienand_dev"
          
          scancentral package -o package.zip -q
          fcli sc-sast scan start -p package.zip --sensor-version $SC_SAST_SENSOR_VERSION --publish-to $(SSC_APP) --store sastscan

          fcli sc-sast scan wait-for ::sastscan:: --interval=30s

          echo Terminating connection with Fortify Platform
          fcli sc-sast session logout
          fcli ssc session logout  
        displayName: Scan Central SAST Scan
        continueOnError: false